### PR TITLE
generalize batchseq to sequence of generic arrays

### LINKED ISSUE #118: `batchseq` for sequences of matrices
I find `batchseq` quite useful to reshape data in preparation for training a recurrent model in Flux.

Unfortunately, looks like `batchseq` only works for sequences of vectors (i.e.1-feature inputs) not sequences of matrices (multi-feature inputs). Consider

```jl
# ex.jl
using MLUtils: batchseq

seqlen = 2

seq_a = [[1, 2, 3] for i in 1:seqlen]
@show seq_a
batched_seq_a = batchseq(seq_a)
@show batched_seq_a

seq_B = [[1 2 3; 4 5 6] for i in 1:seqlen]
@show seq_B
batched_seq_B = batchseq(seq_B)
```

with `MLUtils@v0.2.10` this gives

<details>
<summary>click here to see results</summary>

```
julia> include("ex.jl")
seq_a = [[1, 2, 3], [1, 2, 3]]
batched_seq_a = [[1, 1], [2, 2], [3, 3]]
seq_B = [[1 2 3; 4 5 6], [1 2 3; 4 5 6]]
ERROR: LoadError: MethodError: no method matching rpad(::Matrix{Int64}, ::Int64, ::Nothing)
Closest candidates are:
  rpad(::Any, ::Integer, ::Union{AbstractChar, AbstractString}) at ~/bin/julia-1.7.2/share/julia/base/strings/util.jl:371
  rpad(::AbstractVector, ::Integer, ::Any) at ~/.julia/dev/MLUtils/src/utils.jl:412
  rpad(::Any, ::Integer) at ~/bin/julia-1.7.2/share/julia/base/strings/util.jl:371
  ...
Stacktrace:
 [1] (::MLUtils.var"#130#135"{Nothing, Int64})(x::Matrix{Int64})
   @ MLUtils ./none:0
 [2] iterate
   @ ./generator.jl:47 [inlined]
 [3] collect
   @ ./array.jl:724 [inlined]
 [4] batchseq (repeats 2 times)
   @ ~/.julia/dev/MLUtils/src/utils.jl:433 [inlined]
 [5] top-level scope
   @ ~/.julia/dev/MLUtils/ex.jl:12
 [6] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [7] top-level scope
   @ REPL[1]:1
in expression starting at /home/etetreault/.julia/dev/MLUtils/ex.jl:12
```

</details>

---

- Is making `batchseq` work for sequences of matrices something in the plans for `MLUtils`?
- Would you be willing to accept a PR that adds this functionality?

Thank you very much!

### PR DESCRIPTION
**Pull request by CarloLucibello**
Implement the following behavior for `batchseq`: Given an input list xs containing B arrays of size `* x Li`, where * is common to all arrays and `Li` can vary, return a list of length Lmax where the elements have size `* x B`.

Have to depend on `NNlib` for this, not sure it is worth it. 

Also, we deprecate `rpad` since it is piracy of a Base function in favor of a more generic `rpad_constant` (mimicking the NNlib naming scheme).

Fix #118

### CODE REVIEW

File: test/utils.jl [hunk 1]
```diff
@@ -144,6 +139,11 @@ end
     @test bs[1] == [1, 4]
     @test bs[2] == [2, 5]
     @test bs[3] == [3, -1]
+
+    batchseq([ones(2,4), zeros(2, 3), ones(2,2)]) ==[[1.0 0.0 1.0; 1.0 0.0 1.0]
+                                                    [1.0 0.0 1.0; 1.0 0.0 1.0]
+                                                    [1.0 0.0 0.0; 1.0 0.0 0.0]
+                                                    [1.0 0.0 0.0; 1.0 0.0 0.0]]
```
Comment (etpinard) [inline test/utils.jl:146]: this behaviour looks good to me (author of https://github.com/JuliaML/MLUtils.jl/issues/118) - thanks :+1:
