### PR TITLE
fix rpad and put! ambiguities

### LINKED ISSUE #171: Method ambiguities reported by Aqua
In Julia v1.10, I used Aqua to detect method ambiguities in my package https://github.com/impICNF/ContinuousNormalizingFlows.jl/issues/356 and some of its report were related to this package:

```julia
Ambiguity #94
put!(f!, ringbuffer::MLUtils.RingBuffer) @ MLUtils ~/.julia/packages/MLUtils/n3C0h/src/parallel.jl:219
put!(c::Channel{T}, v) where T @ Base channels.jl:339

Possible fix, define
  put!(::Channel{T}, ::MLUtils.RingBuffer) where T

Ambiguity #100
rpad(v::AbstractVector, n::Integer, p) @ MLUtils deprecated.jl:103
rpad(s, n::Integer, p::Union{AbstractChar, AbstractString}) @ Base strings/util.jl:485

Possible fix, define
  rpad(::AbstractVector, ::Integer, ::Union{AbstractChar, AbstractString})


```

I would appreciate your attention to this issue.

### PR DESCRIPTION
**Pull request by CarloLucibello**
fix #171

### CODE REVIEW

File: src/deprecations.jl [hunk 1]
```diff
@@ -10,3 +10,4 @@
 # Deprecated in v0.3
 import Base: rpad
 @deprecate rpad(v::AbstractVector, n::Integer, p) rpad_constant(v, n, p)
+@deprecate rpad(v::AbstractVector, n::Integer, p::Union{AbstractChar, AbstractString}) = rpad_constant(v, n, p)
```
Comment (ToucheSir) [inline src/deprecations.jl:13]:
```suggestion
@deprecate rpad(v::AbstractVector, n::Integer, p::Union{AbstractChar, AbstractString}) = rpad_constant(v, n, p)

```

File: src/parallel.jl [hunk 2]
```diff
@@ -223,6 +223,7 @@ function Base.put!(f!, ringbuffer::RingBuffer)
     return buf_
 end
 
+Base.put!(::Channel{T}, ::MLUtils.RingBuffer) = error("method not defined for RingBuffer")
```
Comment (ToucheSir) [inline src/parallel.jl:226]:
```suggestion
Base.put!(c::Channel{T}, b::MLUtils.RingBuffer) = throw(MethodError(put!, (c, b)))
```
Could we throw our own MethodError?

**Review by ToucheSir — APPROVED** [review]

**Comment by CarloLucibello** [comment]
test failure is unrelated
